modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "BSD-3-Clause"

[[mods]]
modId = "minoraudioinconvenience"
version = "${version}"
displayName = "Minor Audio Inconvenience"
authors = "dotundrscr"
description = '''
A mod that adds per-sound volume sliders.
'''
#logoFile = ""

[[dependencies.minoraudioinconvenience]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.minoraudioinconvenience]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "minoraudioinconvenience.mixins.json"
